name: shelf_project
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  shelf_router: ^0.7.4

dev_dependencies:
  pedantic: ^1.9.0
